"""Invariant Predictive Music reference engine."""

from .countertime import (
    TimedCandidateScore,
    TimedDecision,
    choose_timed_candidate,
    evaluate_timed_candidate,
    note_candidate,
)
from .countervoice import (
    CandidateAction,
    CandidateDecision,
    CandidateScore,
    CountervoicePolicy,
    StructuralPhase,
    SubsidiaryCandidate,
    SubsidiaryRole,
    choose_candidate,
    evaluate_candidate,
    target_density,
)
from .euclidean import (
    EuclideanPattern,
    euclidean_onsets,
    euclidean_pattern,
    least_aligned_rotation,
    rotation_overlap_count,
)
from .main_voice import (
    MainBranchKind,
    MainDecision,
    MainFuture,
    MainFutureScore,
    MainVoicePolicy,
    calibrated_surprise,
    choose_main_future,
    evaluate_main_futures,
    invariant_similarity,
    surprise_bits,
)
from .midi import render_midi
from .model import IPMConfig, NoteEvent, Voice, VoiceOverlapError
from .randomness import SeededRandom
from .register import FEMALE_LEAD_C4_C5, PitchRegister
from .rhythm import rhythmic_invariant_similarity
from .sonority import (
    ActiveNote,
    SonoritySlice,
    TextureScore,
    VerticalScore,
    contextual_pair_score,
    interval_class,
    interval_prior,
    metrical_strength,
    score_sonority,
    score_texture,
    set_coherence,
    slice_active_sonorities,
)
from .study import StudyResult, compose_study, seed_motif, write_study_files
from .study2 import compose_study_002, seed_motif_002, write_study_002_files

__all__ = [
    "ActiveNote",
    "CandidateAction",
    "CandidateDecision",
    "CandidateScore",
    "CountervoicePolicy",
    "EuclideanPattern",
    "FEMALE_LEAD_C4_C5",
    "IPMConfig",
    "MainBranchKind",
    "MainDecision",
    "MainFuture",
    "MainFutureScore",
    "MainVoicePolicy",
    "NoteEvent",
    "PitchRegister",
    "SeededRandom",
    "SonoritySlice",
    "StructuralPhase",
    "StudyResult",
    "SubsidiaryCandidate",
    "SubsidiaryRole",
    "TextureScore",
    "TimedCandidateScore",
    "TimedDecision",
    "VerticalScore",
    "Voice",
    "VoiceOverlapError",
    "calibrated_surprise",
    "choose_candidate",
    "choose_main_future",
    "choose_timed_candidate",
    "compose_study",
    "compose_study_002",
    "contextual_pair_score",
    "euclidean_onsets",
    "euclidean_pattern",
    "evaluate_candidate",
    "evaluate_main_futures",
    "evaluate_timed_candidate",
    "invariant_similarity",
    "interval_class",
    "interval_prior",
    "least_aligned_rotation",
    "metrical_strength",
    "note_candidate",
    "render_midi",
    "rhythmic_invariant_similarity",
    "rotation_overlap_count",
    "score_sonority",
    "score_texture",
    "seed_motif",
    "seed_motif_002",
    "set_coherence",
    "slice_active_sonorities",
    "surprise_bits",
    "target_density",
    "write_study_002_files",
    "write_study_files",
]
