"""Invariant Predictive Music.

The public v0.2 instrument API lives in :mod:`ipm.engine`. Historical study and
v0.1 primitives remain exported for reproducibility and regression tests.
"""

from .engine import (
    BassControls,
    ExperimentMode,
    InstrumentConfig,
    InstrumentResult,
    PatternLockSpec,
    RhythmControls,
    compose,
    compose_experiment_bundle,
    write_files,
)
from .countertime import (
    TimedCandidateScore,
    TimedDecision,
    choose_timed_candidate,
    evaluate_timed_candidate,
    note_candidate,
)
from .countervoice import (
    CandidateAction,
    CandidateDecision,
    CandidateScore,
    CountervoicePolicy,
    StructuralPhase,
    SubsidiaryCandidate,
    SubsidiaryRole,
    choose_candidate,
    evaluate_candidate,
    target_density,
)
from .euclidean import (
    EuclideanPattern,
    euclidean_onsets,
    euclidean_pattern,
    least_aligned_rotation,
    rotation_overlap_count,
)
from .main_voice import (
    MainBranchKind,
    MainDecision,
    MainFuture,
    MainFutureScore,
    MainVoicePolicy,
    calibrated_surprise,
    choose_main_future,
    evaluate_main_futures,
    invariant_similarity,
    surprise_bits,
)
from .midi import render_midi
from .model import IPMConfig, NoteEvent, Voice, VoiceOverlapError
from .randomness import SeededRandom
from .register import FEMALE_LEAD_C4_B4, PitchRegister, midi_octave_number
from .rhythm import (
    RhythmBudgetPolicy,
    RhythmicPartition,
    choose_rhythmic_partition,
    euclidean_partition,
    realise_partition,
    rhythmic_invariant_similarity,
    rhythmic_partitions,
)
from .sonority import (
    ActiveNote,
    SonoritySlice,
    TextureScore,
    VerticalScore,
    contextual_pair_score,
    interval_class,
    interval_prior,
    metrical_strength,
    score_sonority,
    score_texture,
    set_coherence,
    slice_active_sonorities,
)
from .study import StudyResult, compose_study, seed_motif, write_study_files
from .study2 import compose_study_002, seed_motif_002, write_study_002_files
from .study3 import compose_study_003, write_study_003_files
from .study4 import compose_study_004, write_study_004_files

__all__ = [
    "ActiveNote",
    "BassControls",
    "CandidateAction",
    "CandidateDecision",
    "CandidateScore",
    "CountervoicePolicy",
    "EuclideanPattern",
    "ExperimentMode",
    "FEMALE_LEAD_C4_B4",
    "IPMConfig",
    "InstrumentConfig",
    "InstrumentResult",
    "MainBranchKind",
    "MainDecision",
    "MainFuture",
    "MainFutureScore",
    "MainVoicePolicy",
    "NoteEvent",
    "PatternLockSpec",
    "PitchRegister",
    "RhythmBudgetPolicy",
    "RhythmControls",
    "RhythmicPartition",
    "SeededRandom",
    "SonoritySlice",
    "StructuralPhase",
    "StudyResult",
    "SubsidiaryCandidate",
    "SubsidiaryRole",
    "TextureScore",
    "TimedCandidateScore",
    "TimedDecision",
    "VerticalScore",
    "Voice",
    "VoiceOverlapError",
    "calibrated_surprise",
    "choose_candidate",
    "choose_main_future",
    "choose_rhythmic_partition",
    "choose_timed_candidate",
    "compose",
    "compose_experiment_bundle",
    "compose_study",
    "compose_study_002",
    "compose_study_003",
    "compose_study_004",
    "contextual_pair_score",
    "euclidean_onsets",
    "euclidean_partition",
    "euclidean_pattern",
    "evaluate_candidate",
    "evaluate_main_futures",
    "evaluate_timed_candidate",
    "invariant_similarity",
    "interval_class",
    "interval_prior",
    "least_aligned_rotation",
    "metrical_strength",
    "midi_octave_number",
    "note_candidate",
    "realise_partition",
    "render_midi",
    "rhythmic_invariant_similarity",
    "rhythmic_partitions",
    "rotation_overlap_count",
    "score_sonority",
    "score_texture",
    "seed_motif",
    "seed_motif_002",
    "set_coherence",
    "slice_active_sonorities",
    "surprise_bits",
    "target_density",
    "write_files",
    "write_study_002_files",
    "write_study_003_files",
    "write_study_004_files",
    "write_study_files",
]
