"""Invariant Predictive Music reference engine."""

from .countervoice import (
    CandidateAction,
    CandidateDecision,
    CandidateScore,
    CountervoicePolicy,
    StructuralPhase,
    SubsidiaryCandidate,
    SubsidiaryRole,
    choose_candidate,
    evaluate_candidate,
    target_density,
)
from .main_voice import (
    MainBranchKind,
    MainDecision,
    MainFuture,
    MainFutureScore,
    MainVoicePolicy,
    calibrated_surprise,
    choose_main_future,
    evaluate_main_futures,
    invariant_similarity,
    surprise_bits,
)
from .midi import render_midi
from .model import IPMConfig, NoteEvent, Voice, VoiceOverlapError
from .randomness import SeededRandom
from .sonority import (
    ActiveNote,
    SonoritySlice,
    TextureScore,
    VerticalScore,
    contextual_pair_score,
    interval_class,
    interval_prior,
    metrical_strength,
    score_sonority,
    score_texture,
    set_coherence,
    slice_active_sonorities,
)
from .study import StudyResult, compose_study, seed_motif, write_study_files

__all__ = [
    "ActiveNote",
    "CandidateAction",
    "CandidateDecision",
    "CandidateScore",
    "CountervoicePolicy",
    "IPMConfig",
    "MainBranchKind",
    "MainDecision",
    "MainFuture",
    "MainFutureScore",
    "MainVoicePolicy",
    "NoteEvent",
    "SeededRandom",
    "SonoritySlice",
    "StructuralPhase",
    "StudyResult",
    "SubsidiaryCandidate",
    "SubsidiaryRole",
    "TextureScore",
    "VerticalScore",
    "Voice",
    "VoiceOverlapError",
    "calibrated_surprise",
    "choose_candidate",
    "choose_main_future",
    "compose_study",
    "contextual_pair_score",
    "evaluate_candidate",
    "evaluate_main_futures",
    "invariant_similarity",
    "interval_class",
    "interval_prior",
    "metrical_strength",
    "render_midi",
    "score_sonority",
    "score_texture",
    "seed_motif",
    "set_coherence",
    "slice_active_sonorities",
    "surprise_bits",
    "target_density",
    "write_study_files",
]
